### ISSUE TITLE
Getting error on updating Traceability: Configuration

### ISSUE THREAD

**Issue by dipakverma25** [mantisbt-plugins/traceability#15]
APPLICATION WARNING #101: Configuration option "Custom field for Requirement id" has invalid value "1". (in 'E:\Bitnami\wampstack-5.6.31-0\apps\mantis\htdocs\plugins\Traceability\pages\config_edit.php' line 65)

**Comment by rcasteran** [comment]
Hi @dipakverma25,

This error should be only raised if you attempt to assign the same custom field for both requirement id and test id : you need to configure two different custom fields, and them to assign them separately to requirement id and test id.

Does this help you to solve your problem ?
If not, could you please indicate the mantibt version and the plugin version you use ?

Régis

**Comment by rcasteran** [comment]
No answer from @dipakverma25
